name: RegressionScanStats
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - jupyter
  - matplotlib
  - pandas
  - python=3.8
  - tqdm
  - plotly
  - fastparquet
  - numba
